//
// Created by Sam on 8/25/2026.
//

#ifndef OFFSEASON_BIOBUZZ_PROJECT_DCMOTOREX_HPP
#define OFFSEASON_BIOBUZZ_PROJECT_DCMOTOREX_HPP


class dcMotorEx {

};


#endif //OFFSEASON_BIOBUZZ_PROJECT_DCMOTOREX_HPP
